create table INVENTORY (
    itemId varchar(255) not null,
    link varchar(255),
    location varchar(255),
    quantity integer,
    primary key (itemId)
);

create table ORDERS (
    orderId bigint generated by default as identity,
    customerEmail varchar(255),
    customerName varchar(255),
    discount double not null,
    orderValue double not null,
    retailPrice double not null,
    shippingDiscount double not null,
    shippingFee double not null,
    primary key (orderId)
);

create table ORDER_ITEMS (
    ID bigint generated by default as identity,
    productId varchar(255),
    quantity integer not null,
    ORDER_ID bigint,
    primary key (ID)
);

create table PRODUCT_CATALOG (
    itemId varchar(255) not null,
    description text,
    name varchar(80),
    price double,
    primary key (itemId)
);

alter table ORDER_ITEMS
    add constraint FK2BFF474F65938E8
    foreign key (ORDER_ID)
    references ORDERS;